name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Auth URL to DevHub from secrets
      run: echo ${{ secrets.SFDX_DEVHUB_URL }} > ./SFDX_DEVHUB_URL.txt

    - name: Restore npm Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm

    - name: Install Salesforce CLI
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install sfdx-cli npx

    - name: Update Dependencies
      run: |
        npm update sfdx-cli npx
        npx sfdx-cli --version
        npx sfdx-cli plugins --core

    - name: Authorize DevHub
      run: npx sfdx-cli force:auth:sfdxurl:store --sfdxurlfile ./SFDX_DEVHUB_URL.txt --setalias devhub --setdefaultdevhubusername

    - name: Create Scratch Org
      run: npx sfdx-cli force:org:create --targetdevhubusername devhub --setalias ciorg --setdefaultusername --definitionfile config/project-scratch-def.json --durationdays 1

    - name: Push Source
      run: npx sfdx-cli force:source:push --targetusername ciorg

    - name: Assign Permission Set
      run: npx sfdx-cli force:user:permset:assign --targetusername ciorg --permsetname Mass_Action_Admin

    - name: Load Test Data
      # The test account name, "dca_mass_action: MA Test Account", includes a colon ":", which breaks the yaml parser.
      # As workaround, I put the test name as a secret and bind that to the query instead.
      run: npx sfdx-cli force:data:record:create --targetusername ciorg --sobjecttype Account --values "Name='${{ secrets.TEST_ACCOUNT_NAME_FOR_APEX_TESTS }}'"

    - name: Run Apex Tests
      run: npx sfdx-cli force:apex:test:run --targetusername ciorg --codecoverage --resultformat human --suitenames Mass_Action_Scheduler_Test_Suite --outputdir ./test-results/apex --wait 20

    - name: Collect Flow Test Coverage
      run: |
        npx sfdx-cli force:data:soql:query --targetusername ciorg --usetoolingapi --query "SELECT FlowVersionId, FlowVersion.Definition.DeveloperName, MAX(NumElementsCovered) ItemsCovered, MIN(NumElementsNotCovered) ItemsNotCovered FROM FlowTestCoverage WHERE FlowVersionId IN (SELECT ActiveVersionId FROM FlowDefinition) GROUP BY FlowVersionId, FlowVersion.Definition.DeveloperName" --json | jq -r '[ .result.records[] | ( .ItemsCovered + .ItemsNotCovered ) as $totalLines | ( ( .ItemsCovered / $totalLines * 100 ) | floor ) as $coveredPercent | { id: .FlowVersionId, name: ( .DeveloperName + ".flow-meta.xml" ), totalLines: $totalLines, totalCovered: .ItemsCovered, coveredPercent: $coveredPercent } ]' > ./test-results/apex/test-result-flowcoverage.json
        npx sfdx-cli force:data:soql:query --targetusername ciorg --usetoolingapi --query "SELECT ActiveVersionId, DeveloperName FROM FlowDefinition WHERE ActiveVersionId NOT IN ( SELECT FlowVersionId FROM FlowTestCoverage ) AND ActiveVersion.ProcessType IN ( 'AutoLaunchedFlow', 'CustomEvent', 'InvocableProcess', 'Workflow' )" --json | jq -r '[ .result.records[] | { id: .ActiveVersionId, name: ( .DeveloperName + ".flow-meta.xml" ), totalLines: 0, totalCovered: 0, coveredPercent: 0 } ]' > ./test-results/apex/test-result-noflowcoverage.json

    - name: Upload Code Coverage
      # Uploads code coverage results to Codecov.io.
      # https://codecov.io/gh/douglascayers-org/sfdx-mass-action-scheduler
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Delete Scratch Org
      run: npx sfdx-cli force:org:delete --targetdevhubusername devhub --targetusername ciorg --noprompt
